# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lucifer_sync_pb2 as lucifer__sync__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lucifer_sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LuciferSyncStub(object):
    """============================================================
    LuciferSync — bidirectional sync protocol between master
    and edge devices (desktop / mobile / watch relay).
    Transport: gRPC over mTLS.
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncStream = channel.stream_stream(
                '/lucifer.sync.v1.LuciferSync/SyncStream',
                request_serializer=lucifer__sync__pb2.SyncMessage.SerializeToString,
                response_deserializer=lucifer__sync__pb2.SyncMessage.FromString,
                _registered_method=True)
        self.GetHotSubgraph = channel.unary_unary(
                '/lucifer.sync.v1.LuciferSync/GetHotSubgraph',
                request_serializer=lucifer__sync__pb2.SubgraphRequest.SerializeToString,
                response_deserializer=lucifer__sync__pb2.SubgraphResponse.FromString,
                _registered_method=True)
        self.PushTelemetry = channel.unary_unary(
                '/lucifer.sync.v1.LuciferSync/PushTelemetry',
                request_serializer=lucifer__sync__pb2.TelemetryBatch.SerializeToString,
                response_deserializer=lucifer__sync__pb2.PushAck.FromString,
                _registered_method=True)


class LuciferSyncServicer(object):
    """============================================================
    LuciferSync — bidirectional sync protocol between master
    and edge devices (desktop / mobile / watch relay).
    Transport: gRPC over mTLS.
    ============================================================

    """

    def SyncStream(self, request_iterator, context):
        """Bidirectional streaming: edge pushes deltas, master resolves conflicts
        and streams back confirmed state + any master-side updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotSubgraph(self, request, context):
        """Request hot-subgraph manifest for this device (pull, unary).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTelemetry(self, request, context):
        """Push telemetry batch to master (fire-and-forget, at-least-once).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LuciferSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncStream,
                    request_deserializer=lucifer__sync__pb2.SyncMessage.FromString,
                    response_serializer=lucifer__sync__pb2.SyncMessage.SerializeToString,
            ),
            'GetHotSubgraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHotSubgraph,
                    request_deserializer=lucifer__sync__pb2.SubgraphRequest.FromString,
                    response_serializer=lucifer__sync__pb2.SubgraphResponse.SerializeToString,
            ),
            'PushTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTelemetry,
                    request_deserializer=lucifer__sync__pb2.TelemetryBatch.FromString,
                    response_serializer=lucifer__sync__pb2.PushAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lucifer.sync.v1.LuciferSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lucifer.sync.v1.LuciferSync', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LuciferSync(object):
    """============================================================
    LuciferSync — bidirectional sync protocol between master
    and edge devices (desktop / mobile / watch relay).
    Transport: gRPC over mTLS.
    ============================================================

    """

    @staticmethod
    def SyncStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lucifer.sync.v1.LuciferSync/SyncStream',
            lucifer__sync__pb2.SyncMessage.SerializeToString,
            lucifer__sync__pb2.SyncMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHotSubgraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lucifer.sync.v1.LuciferSync/GetHotSubgraph',
            lucifer__sync__pb2.SubgraphRequest.SerializeToString,
            lucifer__sync__pb2.SubgraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lucifer.sync.v1.LuciferSync/PushTelemetry',
            lucifer__sync__pb2.TelemetryBatch.SerializeToString,
            lucifer__sync__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
